### ISSUE TITLE
Inference on new images

### ISSUE THREAD

**Issue by armheb** [minar09/PGN_tf#4]
Hi thanks for your work, what is the preprocessing steps to test the model on new images? can we just input an image and the output images?
Thanks

**Comment by minar09** [comment]
Hi @armheb , yes I didn't need to do any preprocessing for testing. Just input image with any resolution is okay, and output dimension will be same.

**Comment by armheb** [comment]
Thanks for your quick response, but in the datasets folder there are other files in the edges, list,.. folders, should I just leave them empty?

**Comment by minar09** [comment]
In the current implementation, the dataset requires a list of the image files in text file. For quick testing, I provide both "LIST_PATH" and "DATA_ID_LIST" values with same text file path. You can either do that, or may be change the code a little to read images directly from the dataset folder (Maybe I should do that too).

**Comment by minar09** [comment]
I commented out the edge part, so its not needed.

**Comment by armheb** [comment]
Thank you so much, I'm sorry for my questions but should I first create the labels and edges before making those lists and running the test_pgn.py script?

**Comment by minar09** [comment]
You are welcome. No problem at all. Right now, just images and a list file is okay. No need for labels and edges. You can just generate segmentation for any images.

**Comment by minar09** [comment]
However, if you want to test the performance of the segmentation with metrics e.g. mIoU, than you need the labels/ground-truths, to compare with the generated ones.

**Comment by armheb** [comment]
Great thank you so much, it works fine!
