### ISSUE TITLE
After running test_pgn.py i am getting this error.  

### ISSUE THREAD

**Issue by Sumukh0512** [minar09/PGN_tf#5]
![Screenshot from 2021-07-01 18-47-48](https://user-images.githubusercontent.com/31795364/124131101-18756700-da9d-11eb-8eb1-27a565b3c2cd.png)

**Comment by Sumukh0512** [comment]
@minar09 I am not getting output can you help me.

**Comment by Sumukh0512** [comment]
@minar09 I am able to generate image-parse using this https://github.com/PeikeLi/Self-Correction-Human-Parsing.
This is how the image-parse looks.
![Screenshot from 2021-07-02 22-32-22](https://user-images.githubusercontent.com/31795364/124307387-64034000-db85-11eb-8e4e-ec0d387ab263.png)

This is the TOM tryon result
![Screenshot from 2021-07-02 22-34-35](https://user-images.githubusercontent.com/31795364/124307611-b3497080-db85-11eb-80b6-1de4e4cc7067.png)

I observed one thing whenever I use the updated segmentation [from your processed datasets]that is the image-parse-new file the final result is better

**Comment by Sumukh0512** [comment]
For this updated segmentation taken from the processed datasets of your cp-viton-plus.
![Screenshot from 2021-07-02 22-37-53](https://user-images.githubusercontent.com/31795364/124308187-85186080-db86-11eb-886c-7e686c9b4c7f.png)
 The final tryon result looks like this below,
![Screenshot from 2021-07-02 22-41-51](https://user-images.githubusercontent.com/31795364/124308283-b6912c00-db86-11eb-980c-6e9930d59a6d.png)

**Comment by minar09** [comment]
Hi @Sumukh0512 , yes, that is one of the contributions of CP-VTON+. CP-VTON used segmentation which was missing the neck region label, so we added the label and got better results. Now that, PGN can generate better segmentation with neck-torso label, so we recommend generating segmentation with PGN. It seems you have CUDA/GPU issue. If you don't have a GPU, either you can remove the `.cuda` from the codes, or you can try to utilize colab for running with GPU.

**Comment by Sumukh0512** [comment]
@minar09  thank you so much, I got it.
